name: Skechers workflow
on:
  push:
    branches:
      - test
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to EC2-server on release/sprint-45-test/ branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
jobs:

