jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

  build_and_install:
    name: Build and Install Dependencies
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Remove Git-related files
        run: |
          find . -name '.gitignore' -exec rm -f {} \;
          find . -name '.gitmodules' -exec rm -f {} \;

      - name: Set up Node.js environment
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 12.15.0
