name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2-server on release/sprint-45-test/ branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

  build_and_install:
    name: Build and Install Dependencies
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Remove Git-related files
        run: |
          find . -name ".gitignore" -exec rm -f {} \;
          find . -name ".gitmodules" -exec rm -f {} \;
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '12.15.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ github.workspace }}

      - name: Run npm install
        run: npm run npmInstall
        working-directory: ${{ github.workspace }}
